### ISSUE TITLE
Can't run as root

### ISSUE THREAD

**Issue by seajaysec** [bdombro/chrome-bulk-screenshot#2]
Any way to support running chrome headless as root?

```
❱ chrome-bulk-screenshot -h                                                                                                                                                             master

Config file not found at:
 > config.yml
Using demo config at:
 > /usr/local/share/.config/yarn/global/node_modules/chrome-bulk-screenshot/config-example.yml

Error: Failed to launch chrome!
[0320/200226.515537:ERROR:zygote_host_impl_linux.cc(89)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.


TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/usr/local/share/.config/yarn/global/node_modules/puppeteer/lib/Launcher.js:342:14)
    at Interface.helper.addEventListener (/usr/local/share/.config/yarn/global/node_modules/puppeteer/lib/Launcher.js:331:50)
    at Interface.emit (events.js:194:15)
    at Interface.close (readline.js:379:8)
    at Socket.onend (readline.js:157:10)
    at Socket.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1103:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by bdombro** [comment]
Pull requests are welcome!
